global:
  scrape_interval:     60s
  evaluation_interval: 60s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['10.1.1.1:19090']
        labels:
          instance: prometheus
 
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['10.1.1.1:18080']